---
title: "Animace v ggplot2"
author: author
post_date: 2020-04-25
layout: post
# categories: cat
output: jekyllthat::jekylldown
excerpt_separator: <!--more-->
---

```{r message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(
  fig.path = "../assets/gganimate-covid/"
)
```


```{r message=FALSE, warning=FALSE}
require(tidyverse)
require(gganimate)
```

## Nacitani dat

```{r}
covid <- read_csv("https://covid.ourworldindata.org/data/owid-covid-data.csv", col_types = cols())

num_countries <- 15

data <- covid %>%
  filter(total_cases > 0, location != "World", date >= "2020-03-01") %>%
  group_by(date) %>%
  filter(n() >= num_countries) %>%
  mutate(rank = rank(-total_cases, ties.method = 'first')) %>%
  ungroup() %>%
  filter(rank <= num_countries) %>%
  select(location, date, total_cases, rank)
```

## Staticky graf

```{r}
selected_date <- as.Date("2020-04-30")
data_day <- data %>%
  filter(date == selected_date)

ggplot(data_day, aes(rank)) +
  geom_tile(aes(y = total_cases / 2, height = total_cases, fill = location), width = 0.75) +
  coord_flip(clip = "off") +
  scale_x_reverse(breaks = NULL) +
  scale_fill_discrete(guide = F) +
  geom_text(aes(y = 0, label = paste0(location, " "), color = location), hjust = 'right') +
  scale_color_discrete(guide = F) +
  expand_limits(y = -200000) +
  labs(x = NULL, y = NULL) +
  scale_y_continuous(breaks = 1e5 * seq(0, 10, 2),
                     labels = c("0", paste0(100 * seq(2, 8, 2), "k"), "1M")) +
  ggtitle("Covid-19 potvrzené případy", format(selected_date, "%d/%m/%Y")) +
  theme_minimal()
```

## Animace

```{r}
anim <- ggplot(data, aes(rank)) +
  geom_tile(aes(y = total_cases / 2, height = total_cases, fill = location), width = 0.75) +
  coord_flip(clip = "off") +
  scale_x_reverse(breaks = NULL, limits = c(num_countries + 1, 0.6)) +
  scale_fill_discrete(guide = F) +
  geom_text(aes(y = 0, label = paste0(location, " "), color = location), hjust = 'right') +
  scale_color_discrete(guide = F) +
  labs(x = NULL, y = NULL, title = "Covid-19 potvrzené případy", subtitle = "datum: {frame_time}") +
  transition_time(date) +
  expand_limits(y = -200000) +
  scale_y_continuous(breaks = 1e5 * seq(0, 14, 2),
                     labels = c("0", paste0(100 * seq(2, 8, 2), "k"), "1M", "1.2M", "1.4M")) +
  theme_minimal()

animate(anim, nframes = 450)
# animate(anim, renderer = file_renderer('./frames', overwrite = T))
# animate(anim, nframes = 450, renderer = gifski_renderer("covid.gif"))
```

